### ISSUE TITLE
502 error and backend errors

### ISSUE THREAD

**Issue by JureGrinffin** [libsgh/PanIndex#123]
可以进管理 可以挂盘 可以刷新cookie和缓存
但是看不了文件列表 一看就502（从panindex根目录进入下一级目录就会502）
用docker-compose安装 前端使用nginx反代和提供https CDN使用cloudflare
---
后端报错如下
```
panindex_1  | ERRO[2021-09-22 12:19:51] Get "": unsupported protocol scheme ""        function=GetFileData line=784
panindex_1  | 2021/09/22 12:19:51 http: panic serving 172.20.0.1:37068: runtime error: invalid memory address or nil pointer dereference
panindex_1  | goroutine 135 [running]:
panindex_1  | net/http.(*conn).serve.func1(0xc0007d1180)
panindex_1  |   /usr/local/go/src/net/http/server.go:1824 +0x153
panindex_1  | panic(0xc39e40, 0x13e3380)
panindex_1  |   /usr/local/go/src/runtime/panic.go:971 +0x499
panindex_1  | PanIndex/service.GetFileData(0xc00032fb30, 0x24, 0xc000366d80, 0x11, 0xc000442998, 0x8, 0xc00032fb60, 0x24, 0xc00032fb90, 0x25, ...)
panindex_1  |   /github/workspace/service/service.go:786 +0x4a3
panindex_1  | main.raw(0xc00099a1e0)
panindex_1  |   /github/workspace/main.go:559 +0x174
panindex_1  | main.main.func1(0xc00099a1e0)
panindex_1  |   /github/workspace/main.go:79 +0x836
panindex_1  | github.com/gin-gonic/gin.(*Context).Next(...)
panindex_1  |   /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
panindex_1  | github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc00099a1e0)
panindex_1  |   /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xf4
panindex_1  | github.com/gin-gonic/gin.(*Context).Next(...)
panindex_1  |   /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
panindex_1  | github.com/gin-gonic/gin.serveError(0xc00099a1e0, 0x194, 0x141b2e0, 0x12, 0x12)
panindex_1  |   /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 +0x49
panindex_1  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0004063c0, 0xc00099a1e0)
panindex_1  |   /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 +0x4fc
panindex_1  | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0004063c0, 0xe2b870, 0xc000792700, 0xc0000dbc00)
panindex_1  |   /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
panindex_1  | net/http.serverHandler.ServeHTTP(0xc000248000, 0xe2b870, 0xc000792700, 0xc0000dbc00)
panindex_1  |   /usr/local/go/src/net/http/server.go:2887 +0xa3
panindex_1  | net/http.(*conn).serve(0xc0007d1180, 0xe2d900, 0xc00042c800)
panindex_1  |   /usr/local/go/src/net/http/server.go:1952 +0x8cd
panindex_1  | created by net/http.(*Server).Serve
panindex_1  |   /usr/local/go/src/net/http/server.go:3013 +0x39b

```
---
docker-compose.yml内容如下
```
version: "3"
services:
  panindex:
    image: iicm/pan-index
    restart: always
    volumes:
      - /usr/local/Panindex/data:/app/data
      - /tmp:/tmp:rw

    ports:
      - "[REDACTED]:5238"
```
---
nginx vhost配置文件如下
```
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl_certificate [REDACTED];
  ssl_certificate_key [REDACTED];
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 1400;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  server_name [REDACTED];
  access_log [REDACTED];

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass http://127.0.0.1:36154;
    proxy_http_version 1.1;
  }
}
```

**Comment by libsgh** [comment]
看看你的目录里面是不是隐藏的`README.md`文件，有的话把隐藏去掉

**Comment by JureGrinffin** [comment]
？？？没明白
docker内目录还是宿主机目录
还是onedrive目录

以及md跟502又有什么关系

**Comment by libsgh** [comment]
> ？？？没明白
> docker内目录还是宿主机目录
> 还是onedrive目录
> 
> 以及md跟502又有什么关系
onedrive目录，这里有个bug，如果目录下有README.md，会去获取README.md，但是文件被隐藏过滤了，所以会报错。

**Comment by JureGrinffin** [comment]
可我从来没创建过这玩意啊......
怎么看啊......

**Comment by libsgh** [comment]
> 可我从来没创建过这玩意啊......
> 怎么看啊......

那你有没有设置隐藏文件？

**Comment by JureGrinffin** [comment]
没 我根本不知道这玩意（

**Comment by libsgh** [comment]
如果你是问访问列表页有的上面的错误日志，那就是请求README.md没返回数据，报的错，但是这种情况列表页还是可以展示的，这种情况的原因 要么是没有README.md要么就是有但是隐藏了，**v2.0.6会修复此错误**
如果列表不可以展示，可以分别看下nginx的日志及PnaIndex的请求日志，看下请求有没有到PanIndex，或是日志有无其他错误

**Comment by JureGrinffin** [comment]
我每个根目录都**没有**README.md 话说建一个空的可以吗
是 文件列表都展示不出来
好的 今晚看日志
谢谢了
